config/routes.rb
Rails.application.routes.draw do
 
  root to: 'homes#top'
  get 'rooms/index'
  get 'rooms/show'
  devise_for :users

  resources :users, only: [:show,:index,:edit,:update,:create,:new] do
    get "countsearch" => "users#search"
    resource :relationships, only: [:create,:destroy]
    get :follows, on: :member
    get :followers, on: :member
  end

  resources :books, only:[:create,:index,:show,:edit,:update,:destroy] do
    resources :book_comments, only: [:create,:destroy]
    resource :favorites, only: [:create,:destroy]
  end

  resources :messages, only: [:create, :destroy]
  resources :rooms, only: [:create, :index, :show]

  resources :groups, only: [:new,:index,:create,:edit, :update, :show] do
    get 'groupcreate' => "groups#groupcreate"
    get 'groupdestroy' => 'groups#groupdestroy'
    get 'new/mail' => 'groups#mail_new'
    get 'send/mail' => 'groups#mail_send'
  end
  post 'rooms/:id' => 'rooms#show'

  get 'search' => "searches#search"
  get 'home/about' => 'homes#about'
  
  get 'category_search' => 'categories#search'
  resources :categories, except: [:new, :show]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  is_impressionable

  belongs_to :user
  has_many :favorites,        dependent: :destroy
  has_many :favorited_users , through: :favorites, source: :user
  has_many :book_comments,    dependent: :destroy
  belongs_to :category

  validates :title , presence: true
  validates :body ,  length: {maximum: 200}, presence: true

  validates :rate, presence: true
  validates :rate, numericality: {
    # only_integer: true,
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 0.5,
  }

  scope :created_at_today,          -> { where(created_at: Time.zone.now.all_day) }
  scope :created_at_yesterday,      -> { where(created_at: 1.day.ago.all_day) }
  scope :created_at_two_days_ago  , -> { where(created_at: 2.day.ago.all_day) }
  scope :created_at_three_days_ago, -> { where(created_at: 3.day.ago.all_day) }
  scope :created_at_four_days_ago,  -> { where(created_at: 4.day.ago.all_day) }
  scope :created_at_five_days_ago , -> { where(created_at: 5.day.ago.all_day) }
  scope :created_at_six_days_ago,   -> { where(created_at: 6.day.ago.all_day) }
  scope :created_at_week,           -> {where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) }
  scope :created_at_last_week,      -> {where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) }

  def self.looks(searches,words)
    if searches == "perfect_match"
      @book = Book.where("title LIKE ?" , "#{words}")
      @book = Book.where("body LIKE ?" , "#{words}")
    elsif searches == "forword_match"
      @book = Book.where("title LIKE ?" , "#{words}%")
      @book = Book.where("body LIKE ?" , "#{words}%")
    elsif searches == "backword_match"
      @book = Book.where("title LIKE ?" , "%#{words}")
      @book = Book.where("body LIKE ?" , "%#{words}")
    else
      @book = Book.where("title LIKE ?" , "%#{words}%")
      @book = Book.where("body LIKE ?" , "%#{words}%")
    end
  end

  def self.category_looks(words)
    @category = Category.where('name LIKE ?', "#{words}")
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment_content , presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books, dependent: :destroy
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :book
  belongs_to :user

  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users , through: :group_users
  validates :name, presence: true
  attachment :image
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
  validates :group_id, uniqueness: { scope: :user_id }
end

app/models/message.rb
class Message < ApplicationRecord
  validates :body, length: {maximum: 140}, presence: true

  belongs_to :user
  belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :followed, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_books, through: :favorites, source: :book

  has_many :active_relationships, class_name: "Relationship", foreign_key: :followed_id
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Relationship",foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :followed

  has_many :group_users
  has_many :groups , through: :group_users

  attachment :profile_image

  validates :name, presence: true, length: {minimum: 2,maximum: 20} , uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def liked_by?(book_id)
    self.favorites.where(book_id: book_id).exists?
  end

  def followed_by?(user)
     active_relationships.find_by(follower_id: user.id).present?
  end

  def self.looks(searches, word)
    if searches == "perfect_match"
      @user = User.where( "name LIKE ?" , "#{word}" )
    elsif searches == "forword_match"
      @user = User.where("name LIKE ?" , "%#{word}")
    elsif searches == "backword_match"
      @user = User.where("name LIKE ?" , "#{word}%")
    else
      @user = User.where("name LIKE ?" , "%#{word}%" )
    end
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def new
    @group =Group.new
    @group.users << current_user
  end
  def create
    if @group = Group.create(group_params)
      redirect_to groups_path
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def index
    @groups = Group.all.order(updated_at: :desc)
  end

  def show
    @group = Group.find(params[:id])
    @group_owner = User.find(@group.owner_id)
    @groupmenbers = @group.users

  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if current_user.id == @group.owner_id
      if @group.update(group_params)
        redirect_to groups_path
      else
        redirect_back(fallback_location: root_path)
      end
    end
  end

  def groupcreate
    if groupuser = GroupUser.create(user_id: current_user.id , group_id: params[:group_id])
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def groupdestroy
    group_user = GroupUser.find_by(user_id: current_user.id ,group_id: params[:group_id] )
    if group_user.destroy
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def mail_new
    @group = Group.find(params[:group_id])
  end
  
  def mail_send
    @group = Group.find(params[:group_id])
    group_users = @group.users
    @mail_title = params[:mail_title]
    @mail_content = params[:mail_content]
    ContactMailer.send_mail(@mail_title, @mail_content, group_users).deliver
  end
  
  private
  def group_params
    params.require(:group).permit(:image, :name, :introduction, :owner_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/edit.html.erb
<div class="container">
  <div class="row">
    <div class ="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3>Create Group</h3>
      <%= form_with model:@group do |f| %>
      <div class="form_group">
        <p>グループ名</p>
        <%= f.text_field :name,  class:'form-control name', placeholder: 'グループ名を入力してください' %>
      </div>
      <div class="form_group">
        <p>紹介文</p>
        <%= f.text_area :introduction, class:"form-control"%>
      </div>
      <div class="form_group">
        <p>グループ画像</p>
        <%= f.attachment_field :image, placeholder: 'グループ画像' ,class:"form-control-file user_image" %>
      </div>
      <div class="form_group">
        <%= f.hidden_field :owner_id , value: current_user.id %>
      </div>
      <div class="form_group">
        <%= f.submit "Update Group" ,class:"btn btn-info mt-2"%>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<h3>Groups</h3>
<table class= "table">
  <thead>
    <tr>
      <th></th>
      <th>グループ名</th>
      <th>紹介文</th>
      <th>メンバー数</th>
      <th></th>
    </tr>
  </thead>
  <% @groups.each do |group| %>
  <tbody>
    <tr>
      <td><%= attachment_image_tag group, :image ,:fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg"  %></td>
      <td><%=link_to group.name, group_path(group) %></td>
      <td><%= group.introduction %></td>
      <td><%= group.users.count %></td>
      <% if group.owner_id == current_user.id %>
        <td><%=link_to "Edit", edit_group_path(group) %></td>
      <% end %>
    </tr>
  </tbody>
  <% end %>
</table>

app/views/groups/mail_new.html.erb
<%= form_with url:group_send_mail_path(@group), method: :get, local: true do |f| %>
  <%= f.label :title %>
  <%= f.text_field :mail_title , class:'form_control' %>
  <%= f.label :content %>
  <%= f.text_area :mail_content , class:'form_control' %>
  <%= f.submit '送信' %>
<% end %>

app/views/groups/mail_send.html.erb
<h3>送信が完了しました。</h3>
<p>内容は以下の通りです。</p>
<%= @mail_title %>
<%= @mail_content %>

app/views/groups/new.html.erb
<div class="container">
  <div class="row">
    <div class ="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3>Create Group</h3>
      <%= form_with model:@group do |f| %>
      <div class="form_group">
        <p>グループ名</p>
        <%= f.text_field :name,  class:'form-control name', placeholder: 'グループ名を入力してください' %>
      </div>
      <div class="form_group">
        <p>紹介文</p>
        <%= f.text_area :introduction, class:"form-control"%>
      </div>
      <div class="form_group">
        <p>グループ画像</p>
        <%= f.attachment_field :image, placeholder: 'グループ画像' ,class:"form-control-file user_image" %>
      </div>
      <div class="form_group">
        <%= f.hidden_field :owner_id , value: current_user.id %>
      </div>
      <div class="form_group">
        <%= f.submit "Create Group" ,class:"btn btn-info mt-2"%>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<%= render 'users/list' , user: current_user %>

<h3>Group Detail</h3>
<table class= "table">
  <thead>
    <tr>
      <th></th>
      <th>グループ名</th>
      <th>紹介文</th>
      <th>メンバー</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= attachment_image_tag @group, :image ,:fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg"  %></td>
      <td><%=link_to @group.name, group_path(@group) %></td>
      <td><%= @group.introduction %></td>
        <td class="wrap">
        <% @groupmenbers.each do |member| %>
          <p>
            <%= member.name %>
          </p>
        <% end %>
        </td>

        <% if @group.owner_id == current_user.id %>
        <td><%=link_to "Edit", edit_group_path(@group) %></td>
        <% end %>

        <% unless @group_owner == current_user %>
          <% if @group.users.include?(current_user) %>
            <td><%= link_to "Leave this group" , group_groupdestroy_path(@group) , class:"btn btn-danger" %></td>
          <% else %>
            <td><%=link_to "Join this group", group_groupcreate_path(@group) , class:"btn btn-info" %></td>
          <% end %>
        <% end %>
        <td>
          <%= link_to 'Notice an Event' , group_new_mail_path(@group) %>
        </td>
    </tr>
  </tbody>
</table>