config/routes.rb
Rails.application.routes.draw do
 
  root to: 'homes#top'
  get 'rooms/index'
  get 'rooms/show'
  devise_for :users

  resources :users, only: [:show,:index,:edit,:update,:create,:new] do
    get "countsearch" => "users#search"
    resource :relationships, only: [:create,:destroy]
    get :follows, on: :member
    get :followers, on: :member
  end

  resources :books, only:[:create,:index,:show,:edit,:update,:destroy] do
    resources :book_comments, only: [:create,:destroy]
    resource :favorites, only: [:create,:destroy]
  end

  resources :messages, only: [:create, :destroy]
  resources :rooms, only: [:create, :index, :show]

  resources :groups, only: [:new,:index,:create,:edit, :update, :show] do
    get 'groupcreate' => "groups#groupcreate"
    get 'groupdestroy' => 'groups#groupdestroy'
    get 'new/mail' => 'groups#mail_new'
    get 'send/mail' => 'groups#mail_send'
  end
  post 'rooms/:id' => 'rooms#show'

  get 'search' => "searches#search"
  get 'home/about' => 'homes#about'
  
  get 'category_search' => 'categories#search'
  resources :categories, except: [:new, :show]
  
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_books, through: :favorites, source: :book

  has_many :active_relationships, class_name: "Relationship", foreign_key: :followed_id
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Relationship",foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :followed

  has_many :group_users
  has_many :groups , through: :group_users

  attachment :profile_image

  validates :name, presence: true, length: {minimum: 2,maximum: 20} , uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def liked_by?(book_id)
    self.favorites.where(book_id: book_id).exists?
  end

  def followed_by?(user)
     active_relationships.find_by(follower_id: user.id).present?
  end

  def self.looks(searches, word)
    if searches == "perfect_match"
      @user = User.where( "name LIKE ?" , "#{word}" )
    elsif searches == "forword_match"
      @user = User.where("name LIKE ?" , "%#{word}")
    elsif searches == "backword_match"
      @user = User.where("name LIKE ?" , "#{word}%")
    else
      @user = User.where("name LIKE ?" , "%#{word}%" )
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :baria_user, only: [:edit]

  def show
    @categories = Category.all
    @user = User.find(params[:id])

  # 今日から６日前の投稿数、前日比計算
    @today_book_count          = @user.books.created_at_today.count
    @yesterday_book_count      = @user.books.created_at_yesterday.count
    @two_days_ago_book_count   = @user.books.created_at_two_days_ago.count
    @three_days_ago_book_count = @user.books.created_at_three_days_ago.count
    @four_days_ago_book_count  = @user.books.created_at_four_days_ago.count
    @five_days_ago_book_count  = @user.books.created_at_five_days_ago.count
    @six_days_ago_book_count   = @user.books.created_at_six_days_ago.count

    unless @yesterday_book_count == 0
      @day_before = (@today_book_count.to_f / @yesterday_book_count.to_f).round * 100
    end

    # 今週と先週の投稿数、前週比
    @week_book_count      = @user.books.created_at_week.count
    @last_week_book_count = @user.books.created_at_last_week.count

    unless @last_week_book_count == 0
      @week_before = (@week_book_count.to_f / @last_week_book_count.to_f).round * 100
    end

    @book = Book.new
    @user_books = Book.where(user_id:params[:id]).includes(:favorited_users).sort{|a,b| b.favorited_users.size <=> a.favorited_users.size}
    # @user_books = Book.includes(:favorited_users).sort{|a,b| b.favorited_users.size <=> a.favorited_users.size}
    #上記を追記すると、Book.allが呼び出されてしまう。なので、user.bookを呼び出してから、並び替えの記述をする。
    @current_entry = Entry.where(user_id: current_user.id)
    # Entryモデルからメッセージ相手のレコードを抽出
    @another_entry = Entry.where(user_id: @user.id)

    unless @user.id == current_user.id
      @current_entry.each do |current|
        @another_entry.each do |another|
          # ルームが存在する場合
          if current.room_id == another.room_id
            @is_room = true
            @room_id = current.room_id
          end
        end
      end
      # ルームが存在しない場合は新規作成
      unless @is_room
        @room  = Room.new
        @entry = Entry.new
      end
    end
  end

  def search
    @user = User.find(params[:user_id])
    @books = @user.books

    if params[:created_at] == ""
      @book_counts = "値を入力してください"
    else
      created_at = params[:created_at]
      @book_counts = @books.where(["created_at LIKE ?", "#{created_at}%"]).count
    end
  end

  def index
    @categories = Category.all
    @user  = current_user
    @book  = Book.new
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice:"You have updated user successfully."
    else
      render"edit"
    end
  end

  def follows
    user   = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user   = User.find(params[:id])
    @users = user.followers
  end

  private

  def user_params
    params.require(:user).permit(:name,:profile_image,:introduction)
  end

  def baria_user
    unless User.find(params[:id]).id == current_user.id
    # if User.find(params[:id]).id != current_user.id
    redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_book_counts.html.erb
<div>
  
<h3>投稿数の前日比・前週比</h3>
<table class ="table table-bordered">
  <thead>
    <tr>
      <th class = "text-nowrap">今日の投稿数</th>
      <th class = "text-nowrap">昨日の投稿数</th>
      <th>前日比</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @today_book_count %></td>
      <td><%= @yesterday_book_count %></td>

       <% if @yesterday_book_count == 0 %>
         <td>前日の投稿が0のため計算できません</td>
       <% else %>
         <td><%= @day_before %>% </td>
       <% end %>
    </tr>
  </tbody>
</table>

<table class ="table table-bordered">
  <thead>
    <tr>
      <th class = "text-nowrap">今週の投稿数</th>
      <th class = "text-nowrap">先週の投稿数</th>
      <th>前週比</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td> <%= @week_book_count %></td>
      <td><%= @last_week_book_count %></td>

        <% if @last_week_book_count == 0 %>
          <td>先週の投稿が0のため計算できません</td>
        <% else %>
          <td><%= @week_before %>%</td>
        <% end %>

    </tr>
  </tbody>
</table>
</div>

app/views/users/_chat_btn.html.erb
 <% if current_user.followed_by?(user) && user.followed_by?(current_user)%>
  <% unless user.id == current_user.id %>
    <% if @is_room == true %>
      <td>
        <%= link_to "chatを始める", room_path(@room_id), class: 'btn-sm'%>
      </td>
    <% else %>
      <%= form_with model: @room, url: rooms_path, local: true do |f| %>
        <%= fields_for @entry do |e| %>
          <%= e.hidden_field :user_id, value: user.id %>
        <% end %>
        <td>
          <%= f.submit "ルーム作成" , class: 'btn-sm btn-success'%>
        </td>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/users/_count_search.html.erb
<h4>検索結果</h4>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>投稿数</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= book_counts %></td>
    </tr>
  </tbody>
</table>

app/views/users/_follow_btn.html.erb
  <% if current_user != user %>
    <% if current_user.followed_by?(user) %>
      <td><%=link_to "フォローを外す", user_relationships_path(user.id), method: :delete , class:"btn btn-outline-info" %></td>
    <% else %>
      <td><%=link_to "フォローする", user_relationships_path(user.id), method: :post , class:"btn btn-outline-success btn-block" %></td>
    <% end %>
  <% end %>

app/views/users/_graph.html.erb
<canvas id="myLineChart"></canvas>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.js"></script>

<script>
var ctx = document.getElementById("myLineChart");
var myLineChart = new Chart(ctx, {
  type: 'line',
  data: {
    labels: ['６日前', '５日前', '４日前', '３日前', '２日前', '1日前', '今日'],
    datasets: [
      {
        label: '投稿した本の数',
        data: [
          
          <%= @six_days_ago_book_count.to_s %>, 
          <%= @five_days_ago_book_count.to_s %>,
          <%= @four_days_ago_book_count.to_s %>,
          <%= @three_days_ago_book_count.to_s %>,
          <%= @two_days_ago_book_count.to_s %>,
          <%= @yesterday_book_count.to_s %>,
          <%= @today_book_count.to_s %>
          
          ],
        borderColor: "rgba(0,0,255,1)",
        backgroundColor: "rgba(0,0,0,0)"
      }
    ],
  },
  options: {
    title: {
      display: true,
      text: '７日間の投稿数比較'
    },
    scales: {
      yAxes: [{
        ticks: {
          suggestedMax: 10,
          suggestedMin: 0,
          stepSize: 1,
          callback: function(value, index, values){
            return  value 
          }
        }
      }]
    },
  }
});
</script>

app/views/users/_list.html.erb
  <h2>User info</h2>

  <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
  <table class="table">
    <tbody>
      <tr>
        <th>name</th>
        <th class = "text-nowrap"><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
      <tr>
        <th>follows</th>
        <th><%=link_to user.followings.count ,follows_user_path(user.id) %></th>
      </tr>
      <tr>
        <th>followers</th>
        <th><%=link_to user.followers.count , followers_user_path(user.id) %></th>
      </tr>
    </tbody>
  </table>
   <%= link_to edit_user_path(user.id),class:"btn btn-outline-secondary btn-block" do %>
    <i class ="fas fa-user-cog"></i>
    <% end %>

app/views/users/_userbooks.html.erb
<h2>Books</h2>

<table class ="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan=3></th>
    </tr>
  </thead>

 <% user_books.each do|book| %>
  <tbody>
    <tr>

     <td>
       <%=link_to user_path(book.user.id) do %>
       <%= attachment_image_tag book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg" ,size: "40x40"%>
       <% end %>
     </td>

     <td>
       <%=link_to book_path(book.id) do %>
       <%=book.title %>
       <% end %>
     </td>

     <td>
       <%= book.body %>
     </td>
     <td id ="Favorites-buttons<%= book.id%>">
       <%= render partial: "favorites/like", locals: { book: book }%>
     </td>
     <td class ='example'>
       <span>コメント数：<%= book.book_comments.count %></span>
     </td>

     <td>
       <div id="star-rate-<%= book.id %>"></div>
       <script>
         // 繰り返し処理でもidをidを一意にできるようにnote_idを入れる
       $('#star-rate-<%= book.id %>').raty({
         size: 36,
         starOff:  '<%= asset_path('star-off.png') %>',
         starOn : '<%= asset_path('star-on.png') %>',
         starHalf: '<%= asset_path('star-half.png') %>',
         half: true,
         // 読み込みだけで入力できない
         readOnly: true,
         score: <%= book.rate %>,
        });
       </script>
     </td>
    </tr>
  </tbody>
 <% end %>
</table>

app/views/users/_week_book_counts.html.erb
<h2>7日間分の投稿数</h2>
<table class ="table table-bordered" >
  <thead>
    <tr>
      <th>６日前</th>
      <th>５日前</th>
      <th>４日前</th>
      <th>３日前</th>
      <th>２日前</th>
      <th>１日前</th>
      <th>今日</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      
      <td><%= @six_days_ago_book_count %></td>
      <td><%= @five_days_ago_book_count %></td>
      <td><%= @four_days_ago_book_count %></td>
      <td><%= @three_days_ago_book_count %></td>
      <td><%= @two_days_ago_book_count %></td>
      <td><%= @yesterday_book_count %></td>
      <td><%= @today_book_count %></td>

    </tr>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class ="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info </h2>
      <% if @user.errors.any? %>
        <div id="error_explanation" >
          <h3><%= @user.errors.count%>errors prohibited this obj from being saved:</h3><br>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li> <%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_with model:@user,local:true do |f| %>

        <div class="form_group">
          <%= f.label :name %><br />
          <%= f.text_field :name, autofocus:true, autocomplete:"name" ,class:"form-control name" %>
        </div>

        <div class="form_group">
          <%= f.label :profile_image %><br />
          <%= f.attachment_field :profile_image ,class:"form-control-file user_image" %>
        </div>

        <div class="form_group">
          <%= f.label :introduction %><br />
          <%= f.text_area :introduction, autofocus:true, autocomplete:"introduction",class:"form-control introduction" %>
        </div>

        <div class="form_group">
          <%= f.submit "Update User" ,class:"btn btn-secondary" %>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<h1>Followers Users</h1>
  <table class = "table table-hover table-inverse">
    <thead>
      <tr>

        <th>image</th>
        <th>name</th>
        <th colspan=3 ></th>
      </tr>
    </thead>

    <% @users.each do |user| %>
    <tbody>
      <tr>

        <td><%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.followings.count %></td>
        <td>フォロワー数：<%= user.followers.count %></td>
        <td><%= link_to "Show" ,user_path(user) %></td>

      </tr>
    </tbody>
    <% end %>
  </table>

app/views/users/follows.html.erb
<div class ="container">
  <div class="row">
    <div class ="col">

      <h1>Followes Users</h1>
      <table class = "table table-hover table-inverse">
        <thead>
          <tr>

            <th>image</th>
            <th>name</th>
            <th colspan=3 ></th>
          </tr>
        </thead>

        <% @users.each do |user| %>
        <tbody>
          <tr>

            <td><%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></td>
            <td><%= user.name %></td>
            <td>フォロー数：<%= user.followings.count %></td>
            <td>フォロワー数：<%= user.followers.count %></td>
            <td><%= link_to "Show" ,user_path(user) %></td>

          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class ="container px-5 px-sm-0">
  <div class="row">
    <div class ="col-md-3">
      <%= render 'list',user:@user %>
      <%= render 'users/follow_btn' , user:@user %>
      <%= render 'users/chat_btn' , user:@user %>
      <%= render 'books/newbook' , book:@book, categories:@categories %>
    </div>
    <div class ="col-md-8 offset-md-1">

      <h2>Users</h2>
      <%= link_to  "グループを作成する", new_group_path %>|<%= link_to "グループ一覧" ,groups_path %>
      <table class ="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan =3></th>
          </tr>
        </thead>

        <% @users.each do |user| %>
        <tbody>
          <tr>
            <td> <%= attachment_image_tag user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %> </td>
            <td> <%= user.name %> </td>

            <td>フォロー数：<%= user.followings.count %></td>
            <td>フォロワー数：<%= user.followers.count %></td>
            <% if current_user != user %>
              <% if current_user.followed_by?(user) %>
                <td><%=link_to "フォローを外す", user_relationships_path(user.id), method: :delete , class:"btn btn-outline-info btn-block" %></td>
              <% else %>
                <td><%=link_to "フォローする", user_relationships_path(user.id), method: :post , class:"btn btn-outline-success btn-block" %></td>
              <% end %>
            <% end %>
            <td>
              <div data-turbolinks="false">
                <%=link_to "Show" ,user_path(user.id)  %>
              </div>
            </td>
          </tr>
        </tbody>
        <% end %>

      </table>
    </div>
  </div>
</div>

app/views/users/search.js.erb
$('#countsearch').html("<%= j(render partial: 'users/count_search',locals: {book_counts:@book_counts}) %>");

app/views/users/show.html.erb
<div class ="container px-5 px-sm-0">

  <div class="row">
    <div class ="col-md-3">

      <%= render'list',user:@user,book:@book %>
      <%= render 'users/follow_btn' , user:@user %>
      <%= render 'users/chat_btn' , user:@user %>
      <%= render 'books/newbook' , book:@book, categories:@categories %>

    </div>
    <div class ="col-md-8 offset-md-1">

  　　<div id="userbooks">
        <%=render 'users/userbooks' , user_books:@user_books %>
  　　</div>

      <%#= render 'users/book_counts' %>

      <%#= render 'users/week_book_counts'%>

      <%#= render 'users/graph' %>

      <div>
        <%= form_with url: user_countsearch_path(@user) , method: :get , remote: true do |f| %>
          <%= f.date_field :created_at  %>
          <%= f.submit "検索" ,class: 'btn btn-primary'%>
        <% end %>
      </div>

        <div id="countsearch">

             <%= render 'users/count_search', book_counts:@book_counts %>

        </div>

    </div>
  </div>
</div>