config/routes.rb
Rails.application.routes.draw do
 
  root to: 'homes#top'
  get 'rooms/index'
  get 'rooms/show'
  devise_for :users

  resources :users, only: [:show,:index,:edit,:update,:create,:new] do
    get "countsearch" => "users#search"
    resource :relationships, only: [:create,:destroy]
    get :follows, on: :member
    get :followers, on: :member
  end

  resources :books, only:[:create,:index,:show,:edit,:update,:destroy] do
    resources :book_comments, only: [:create,:destroy]
    resource :favorites, only: [:create,:destroy]
  end

  resources :messages, only: [:create, :destroy]
  resources :rooms, only: [:create, :index, :show]

  resources :groups, only: [:new,:index,:create,:edit, :update, :show] do
    get 'groupcreate' => "groups#groupcreate"
    get 'groupdestroy' => 'groups#groupdestroy'
    get 'new/mail' => 'groups#mail_new'
    get 'send/mail' => 'groups#mail_send'
  end
  post 'rooms/:id' => 'rooms#show'

  get 'search' => "searches#search"
  get 'home/about' => 'homes#about'
  
  get 'category_search' => 'categories#search'
  resources :categories, except: [:new, :show]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  is_impressionable

  belongs_to :user
  has_many :favorites,        dependent: :destroy
  has_many :favorited_users , through: :favorites, source: :user
  has_many :book_comments,    dependent: :destroy
  belongs_to :category

  validates :title , presence: true
  validates :body ,  length: {maximum: 200}, presence: true

  validates :rate, presence: true
  validates :rate, numericality: {
    # only_integer: true,
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 0.5,
  }

  scope :created_at_today,          -> { where(created_at: Time.zone.now.all_day) }
  scope :created_at_yesterday,      -> { where(created_at: 1.day.ago.all_day) }
  scope :created_at_two_days_ago  , -> { where(created_at: 2.day.ago.all_day) }
  scope :created_at_three_days_ago, -> { where(created_at: 3.day.ago.all_day) }
  scope :created_at_four_days_ago,  -> { where(created_at: 4.day.ago.all_day) }
  scope :created_at_five_days_ago , -> { where(created_at: 5.day.ago.all_day) }
  scope :created_at_six_days_ago,   -> { where(created_at: 6.day.ago.all_day) }
  scope :created_at_week,           -> {where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) }
  scope :created_at_last_week,      -> {where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) }

  def self.looks(searches,words)
    if searches == "perfect_match"
      @book = Book.where("title LIKE ?" , "#{words}")
      @book = Book.where("body LIKE ?" , "#{words}")
    elsif searches == "forword_match"
      @book = Book.where("title LIKE ?" , "#{words}%")
      @book = Book.where("body LIKE ?" , "#{words}%")
    elsif searches == "backword_match"
      @book = Book.where("title LIKE ?" , "%#{words}")
      @book = Book.where("body LIKE ?" , "%#{words}")
    else
      @book = Book.where("title LIKE ?" , "%#{words}%")
      @book = Book.where("body LIKE ?" , "%#{words}%")
    end
  end

  def self.category_looks(words)
    @category = Category.where('name LIKE ?', "#{words}")
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment_content , presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books, dependent: :destroy
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :book
  belongs_to :user

  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users , through: :group_users
  validates :name, presence: true
  attachment :image
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
  validates :group_id, uniqueness: { scope: :user_id }
end

app/models/message.rb
class Message < ApplicationRecord
  validates :body, length: {maximum: 140}, presence: true

  belongs_to :user
  belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :followed, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_books, through: :favorites, source: :book

  has_many :active_relationships, class_name: "Relationship", foreign_key: :followed_id
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Relationship",foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :followed

  has_many :group_users
  has_many :groups , through: :group_users

  attachment :profile_image

  validates :name, presence: true, length: {minimum: 2,maximum: 20} , uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def liked_by?(book_id)
    self.favorites.where(book_id: book_id).exists?
  end

  def followed_by?(user)
     active_relationships.find_by(follower_id: user.id).present?
  end

  def self.looks(searches, word)
    if searches == "perfect_match"
      @user = User.where( "name LIKE ?" , "#{word}" )
    elsif searches == "forword_match"
      @user = User.where("name LIKE ?" , "%#{word}")
    elsif searches == "backword_match"
      @user = User.where("name LIKE ?" , "#{word}%")
    else
      @user = User.where("name LIKE ?" , "%#{word}%" )
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :baria_book , only: [:edit]
  impressionist action: [:show]

  def create
    @user = current_user
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id

    if @book.save
        redirect_to book_path(@book.id), notice:'You have created book successfully.'
    else
       render"index"
    end
  end

  def index
    @user = current_user
    @book = Book.new
    @categories = Category.all
  # ソートさせる記述
  #   sort_word = params[:sort_word]
  # if sort_word.present?
  #   if sort_word == "new"
  #     @books = Book.all.order(created_at: :desc)
  #   elsif sort_word == "rate"
  #     @books = Book.all.order(rate: :desc)
  #   end
  # else
  if params[:sort]
     @books = Book.all.order(params[:sort])
  else
    to = Time.current.at_end_of_day
    from = (to - 6.day).at_beginning_of_day
    @books = Book.all.includes(:favorited_users).
      sort {|a,b|
        b.favorited_users.includes(:favorites).where(created_at: from...to).size <=>
        a.favorited_users.includes(:favorites).where(created_at: from...to).size
      }
  end
# end
  end

  def show
    @categories = Category.all
    @book = Book.new
    @user_book = Book.find(params[:id])
    @user = @user_book.user
    @book_comments = @user_book.book_comments.all
    @book_comment = current_user.book_comments.new
    impressionist(@user_book, nil, unique: [:session_hash.to_s])
  end

  def edit
    @book=Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id),notice:"You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

   private

   def book_params
     params.require(:book).permit(:title,:body,:rate,:category_id)
   end

   def baria_book
     unless Book.find(params[:id]).user_id == current_user.id
    # Book.find(params[:id]).user_id =! current_user.id
     redirect_to books_path
     end
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_index.html.erb
<h2>Books</h2>

   <%#= link_to "新着順", books_path(sort_word: "new")  %>
   <%= link_to "新着順", books_path(sort: 'created_at DESC') %>
   <span>|</span>
   <%#= link_to "評価の高い順" , books_path(sort_word: "rate") %>
   <%= link_to "評価が高い順", books_path(sort: 'rate DESC') %>

<table class="table table-hover table-inverse">
  <therd>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Category</th>
      <th colspan=6></th>
    </tr>
  </therd>

  <% books.each do |book| %>
  <tbody>
    <tr>

      <td>
      <%= link_to user_path(book.user.id) do %>
      <%= attachment_image_tag book.user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg"%>
      <% end %>
      </td>

      <td>
        <%= link_to book_path(book.id) do %>
        <%= book.title %>
        <% end %>
      </td>

      <td>
        <%= book.body %>
      </td>

      <td>
        <%= link_to book.category.name, category_search_path(category_word: book.category.name) %>
      </td>

      <td id ="Favorites-buttons<%= book.id%>">
       <%= render partial: "favorites/like", locals: { book: book }%>
     </td>

      <td class ='example'>
        コメント数：<%=book.book_comments.count %>
      </td>
      <td>
        閲覧数: <%= book.impressionist_count(:filter=>:session_hash) %>
      </td>

      <td>
        <div id="star-rate-<%= book.id %>"></div>
        <script>
          // 繰り返し処理でもidをidを一意にできるようにnote_idを入れる
        $('#star-rate-<%= book.id %>').raty({
          size: 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          half: true,
          // 読み込みだけで入力できない
          readOnly: true,
          score: <%= book.rate %>,
         });
        </script>
      </td>
    </tr>
  </tbody>
  <% end %>
</table>

app/views/books/_newbook.html.erb
 <div>
  <h2 class="mt-3">New book</h2>
  <%= form_with model:book,local:true do |f| %>

    <div class="form-group">
      <label for="book-title">Title</label>
      <%= f.text_field :title , class:"form-control book_title" %>
    </div>

    <div class="form-group">
      <label for="book-opinion">Opinion</label>
      <%= f.text_area :body , class:"form-control book_body" %>
    </div>

    <div class="form-group">
      <label for="book-category">Category</label>
      <%= f.collection_select(:category_id, categories, :id, :name) %>
    </div>

    <div class="form-group row" id="star">
      <%= f.label :rate,'Rate:', class:'p-1' %>
      <%= f.hidden_field :rate, id: :review_star %>
    </div>

    <div class="form-group">
      <%= f.submit'Create Book' , class: "btn btn-success" %>
    </div>

  <% end %>
  <%= link_to 'ジャンルを追加する', categories_path %>


  <script type="text/javascript">
   <!-- 評価 -->
    $('#star').raty({
      size     : 36,
      starOff:  '<%= asset_path('star-off.png') %>',
      starOn : '<%= asset_path('star-on.png') %>',
      starHalf: '<%= asset_path('star-half.png') %>',
      scoreName: 'book[rate]',
      half: true,
    });
  </script>

</div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class ="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <% if @book.errors.any? %>
        <div id="error_explanation" >
          <h3><%= @book.errors.count%>errors prohibited this obj from being saved:</h3><br>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li> <%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_with model:@book,local:true do |f| %>

        <div class="form-group">
          <label for="book-title">Title</label>
          <%= f.text_field :title , class:"form-control book_title" %>
        </div>

        <div class="form-group">
          <label for="book-opinion">Opinion</label>
          <%= f.text_area :body , class:"form-control book_body" %>
        </div>

        <div class="form-group">
          <label for="book-category">Category</label>
          <%= f.collection_select(:category_id, @categories, :id, :name) %>
        </div>

        <div class="form-group">
          <%= f.submit'Update Book',class:"btn btn-success" %>
        </div>

        <td>
          <div id="star-rate-<%= @book.id %>"></div>
          <script>
            // 繰り返し処理でもidをidを一意にできるようにnote_idを入れる
          $('#star-rate-<%= @book.id %>').raty({
            size: 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            half: true,
            // 読み込みだけで入力できない
            readOnly: true,
            score: <%= @book.rate %>,
           });
          </script>
        </td>

      <% end %>

      <%= link_to "Show" , book_path(@book.id)%>
      |
      <%= link_to "Back" , books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <div id="error_explanation" >
    <h3><%= @book.errors.count%>errors prohibited this obj from being saved:</h3><br>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li> <%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class ="container px-5 px-sm-0">
  <div class="row">
    <div class ="col-md-3">

      <%= render'users/list',user:@user %>
      <%= render 'users/follow_btn' , user:@user %>
      <%= render 'users/chat_btn' , user:@user %>
      <%= render 'books/newbook' , book:@book %>

    </div>
    <div class ="col-md-8 offset-md-1" id="books">

       <%= render 'books/index', books:@books %>

    </div>
 </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <%= render 'users/list',user:@user,book:@book%>

      <h2>Book detail</h2>
      <table class="table">
        <therd>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th>Category</th>
            <th colspan=8></th>

          </tr>
      　</therd>
        <tbody>
          <tr>

            <td>
              <div data-turbolinks="false">
              <%=link_to user_path(@user.id) do %>
              <%= attachment_image_tag @user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %><br>
              <%=@user.name %>
              <% end %>
              </div>
            </td>

            <td>
              <%=link_to book_path(@user_book.id) do%>
              <%=@user_book.title %>
              <% end %>
            </td>

            <td>
              <%= @user_book.body %>
            </td>

            <td>
              <%= @user_book.category.name %>
            </td>
            
            <td id ="Favorites-buttons<%= @user_book.id %>">
             <%= render partial: "favorites/like", locals: { book: @user_book }%>
           </td>

            <td id = "comments_count" >
              <%=render partial: "book_comments/count" , locals: { book: @user_book}%>
            </td>
            <td>
             閲覧数: <%= @user_book.impressionist_count(:filter=>:session_hash) %>
            </td>
            
            <td>
              <div id="star-rate-<%= @user_book.id %>"></div>
              <script>
                // 繰り返し処理でもidをidを一意にできるようにnote_idを入れる
              $('#star-rate-<%= @user_book.id %>').raty({
                size: 36,
                starOff:  '<%= asset_path('star-off.png') %>',
                starOn : '<%= asset_path('star-on.png') %>',
                starHalf: '<%= asset_path('star-half.png') %>',
                half: true,
                // 読み込みだけで入力できない
                readOnly: true,
                score: <%= @user_book.rate %>,
               });
              </script>
            </td>
                
            <% if @user_book.user == current_user %>

            <td>
              <%=link_to edit_book_path(@user_book.id) ,class:"btn btn-sm btn-success" do %>
              Edit
              <% end %>
            </td>

            <td>
              <%=link_to book_path(@user_book.id), method: :delete ,class:"btn btn-sm btn-danger " ,method: :delete, data: {confirm: "本当に消しますか？"}  do%>
              Destroy
              <% end %>
            </td>
            <% end %>

          </tr>
        </tbody>
      </table>
      <h2>Comment</h2>
      <table class="table">
        <tbody id ="comments_area">
          <%= render partial: "book_comments/comment" , locals: { book_comments: @book_comments } %>
        </tbody>
      </table>

      <%= form_with model: [@user_book,@book_comment], method: :post do |f| %>
      <div class="form_group">
      <%= f.text_area :comment_content , class:"form-control"%>
      <%= f.hidden_field :book_id, value: @user_book.id %>
      </div>
      <div class="form_group mt-3">
      <%= f.submit "送信" , class:"btn btn-success" %>
      </div>
      <% end %>

  </div>
</div>