config/routes.rb
Rails.application.routes.draw do
 
  root to: 'homes#top'
  get 'rooms/index'
  get 'rooms/show'
  devise_for :users

  resources :users, only: [:show,:index,:edit,:update,:create,:new] do
    get "countsearch" => "users#search"
    resource :relationships, only: [:create,:destroy]
    get :follows, on: :member
    get :followers, on: :member
  end

  resources :books, only:[:create,:index,:show,:edit,:update,:destroy] do
    resources :book_comments, only: [:create,:destroy]
    resource :favorites, only: [:create,:destroy]
  end

  resources :messages, only: [:create, :destroy]
  resources :rooms, only: [:create, :index, :show]

  resources :groups, only: [:new,:index,:create,:edit, :update, :show] do
    get 'groupcreate' => "groups#groupcreate"
    get 'groupdestroy' => 'groups#groupdestroy'
    get 'new/mail' => 'groups#mail_new'
    get 'send/mail' => 'groups#mail_send'
  end
  post 'rooms/:id' => 'rooms#show'

  get 'search' => "searches#search"
  get 'home/about' => 'homes#about'
  
  get 'category_search' => 'categories#search'
  resources :categories, except: [:new, :show]
  
end

app/models/book.rb
class Book < ApplicationRecord
  is_impressionable

  belongs_to :user
  has_many :favorites,        dependent: :destroy
  has_many :favorited_users , through: :favorites, source: :user
  has_many :book_comments,    dependent: :destroy
  belongs_to :category

  validates :title , presence: true
  validates :body ,  length: {maximum: 200}, presence: true

  validates :rate, presence: true
  validates :rate, numericality: {
    # only_integer: true,
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 0.5,
  }

  scope :created_at_today,          -> { where(created_at: Time.zone.now.all_day) }
  scope :created_at_yesterday,      -> { where(created_at: 1.day.ago.all_day) }
  scope :created_at_two_days_ago  , -> { where(created_at: 2.day.ago.all_day) }
  scope :created_at_three_days_ago, -> { where(created_at: 3.day.ago.all_day) }
  scope :created_at_four_days_ago,  -> { where(created_at: 4.day.ago.all_day) }
  scope :created_at_five_days_ago , -> { where(created_at: 5.day.ago.all_day) }
  scope :created_at_six_days_ago,   -> { where(created_at: 6.day.ago.all_day) }
  scope :created_at_week,           -> {where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) }
  scope :created_at_last_week,      -> {where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) }

  def self.looks(searches,words)
    if searches == "perfect_match"
      @book = Book.where("title LIKE ?" , "#{words}")
      @book = Book.where("body LIKE ?" , "#{words}")
    elsif searches == "forword_match"
      @book = Book.where("title LIKE ?" , "#{words}%")
      @book = Book.where("body LIKE ?" , "#{words}%")
    elsif searches == "backword_match"
      @book = Book.where("title LIKE ?" , "%#{words}")
      @book = Book.where("body LIKE ?" , "%#{words}")
    else
      @book = Book.where("title LIKE ?" , "%#{words}%")
      @book = Book.where("body LIKE ?" , "%#{words}%")
    end
  end

  def self.category_looks(words)
    @category = Category.where('name LIKE ?', "#{words}")
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment_content , presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books, dependent: :destroy
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :book
  belongs_to :user

  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users , through: :group_users
  validates :name, presence: true
  attachment :image
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
  validates :group_id, uniqueness: { scope: :user_id }
end

app/models/message.rb
class Message < ApplicationRecord
  validates :body, length: {maximum: 140}, presence: true

  belongs_to :user
  belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :followed, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_books, through: :favorites, source: :book

  has_many :active_relationships, class_name: "Relationship", foreign_key: :followed_id
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Relationship",foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :followed

  has_many :group_users
  has_many :groups , through: :group_users

  attachment :profile_image

  validates :name, presence: true, length: {minimum: 2,maximum: 20} , uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def liked_by?(book_id)
    self.favorites.where(book_id: book_id).exists?
  end

  def followed_by?(user)
     active_relationships.find_by(follower_id: user.id).present?
  end

  def self.looks(searches, word)
    if searches == "perfect_match"
      @user = User.where( "name LIKE ?" , "#{word}" )
    elsif searches == "forword_match"
      @user = User.where("name LIKE ?" , "%#{word}")
    elsif searches == "backword_match"
      @user = User.where("name LIKE ?" , "#{word}%")
    else
      @user = User.where("name LIKE ?" , "%#{word}%" )
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <%= link_to "Bookers" , root_path ,class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class= "navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li>
            <div data-turbolinks="false">
              <%= link_to "Home", user_path(current_user.id) ,class: 'fas fa-home nav-link text-light' %>
            </div>
          </li>
          <li>
            <%= link_to "Users" , users_path ,class: 'fas fa-users nav-link text-light' %>
          </li>
          <li>
            <%= link_to "Books" , books_path , class: 'fas fa-book-open nav-link text-light' %>
          </li>
          <li>
            <%= link_to "logout" , destroy_user_session_path, class: 'fas fa-sign-out-alt nav-link text-light' , method: :delete %>
          </li>
          <li>
            <%= form_with url:category_search_path , method: :get , local: :true do |f| %>
              <%= f.text_field :category_word %>
              <%= f.submit "検索" %>
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to root_path , class: 'fas fa-home nav-link text-light' do %>Home<% end %>
          </li>
          <li>
            <%= link_to home_about_path , class: 'fas fa-link nav-link text-light' do %>About<% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path , class: 'fas fa-user-plus nav-link text-light' do %>sign up<% end %>
          </li>
          <li>
            <%= link_to new_user_session_path , class: 'fas fa-sign-in-alt nav-link text-light' do %>login<% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  </head>
  <header>
    <%=render 'layouts/header' %>
    <% if user_signed_in? %>
    <%=render 'searches/search_window' %>
    <% end %>
  </header>
  <body>
    <main>
      <p id="notice">
        <%= flash[:notice] %>
      </p>

     

      <%= yield %>
    </main>
    <footer>
      <div class = "container mt-5">
        <div class ="row">
          <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>